### PR TITLE
Use Gradle executable and JAVA_HOME from preferences

### LINKED ISSUE #141: Plugin does not seem to work when you don't have Gradle installed
**Describe the bug**
All our projects are using gradle wrapper, so Gradle itself is not installed to my system and its not in my path. Does it mean that the plugin does not work with Gradle wrapper? Connecting to Xray works and CI tab works as well. Its the local tab thats failing.

**Versions**
- IntelliJ IDEA 2021.1.3 Ultimate Edition
- JFrog IDEA plugin version: 1.9.1
- Operating system: MacOS 10.15.7
- Xray version: 3.27.2

**Additional context**
```
20:44	JFrog Xray scan failed: [ERROR] Could not scan Gradle project dependencies, because Gradle CLI is not in the PATH.

20:44	JFrog Xray scan failed
			[ERROR] 
			java.lang.NullPointerException
			at com.jfrog.ide.common.scan.ScanManagerBase.extractComponents(ScanManagerBase.java:132)
			at com.jfrog.ide.common.scan.ScanManagerBase.scanAndCacheArtifacts(ScanManagerBase.java:150)
			at com.jfrog.ide.idea.scan.ScanManager.scanAndUpdate(ScanManager.java:108)
			at com.jfrog.ide.idea.scan.ScanManager$1.run(ScanManager.java:145)
			at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
			at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
			at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
			at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
			at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
			at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgr... (show balloon)

```

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/jfrog-idea-plugin/actions/workflows/test.yml) passed. If this feature is not already covered by the tests, I added new tests.
-----

Depends on https://github.com/jfrog/ide-plugins-common/pull/46
Resolves #141 and possibly #142

### CODE REVIEW

File: src/main/java/com/jfrog/ide/idea/log/Logger.java [hunk 1]
```diff
@@ -104,4 +107,9 @@ private static String prependPrefix(String message, NotificationType notificatio
         }
         return "[INFO] " + message;
     }
+
+    public static void openSettings(String details, Project project, Class<? extends Configurable> configurable) {
```
Comment (eyalbe4) [inline src/main/java/com/jfrog/ide/idea/log/Logger.java:111]: openSettings --> addOpenSettingsLink

Let's also add a clear usage description to the method. We can also add this as an example - 
```
Logger.openSettings("It looks like Gradle home was not properly set in your project. Click <a href=\"#settings\">here</a> to set Gradle home.", project, GradleConfigurable.class);
```

File: src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java [hunk 2]
```diff
@@ -62,4 +75,66 @@ protected LocalInspectionTool getInspectionTool() {
     protected void buildTree(boolean shouldToast) throws IOException {
         setScanResults(gradleTreeBuilder.buildTree(getLog()));
     }
+
+    /**
+     * Extracts the chosen Gradle executable path from the Gradle plugin. If Gradle is not installed, throw an exception.
```
Comment (eyalbe4) [inline src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java:80]: Let's also explain when this method returns null.

File: src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java [hunk 3]
```diff
@@ -34,7 +46,8 @@
     GradleScanManager(Project project, String basePath) throws IOException {
         super(project, basePath, ComponentPrefix.GAV);
         getLog().info("Found Gradle project: " + getProjectName());
-        gradleTreeBuilder = new GradleTreeBuilder(Paths.get(basePath), EnvironmentUtil.getEnvironmentMap());
+        Map<String, String> env = Maps.newHashMap(EnvironmentUtil.getEnvironmentMap());
+        gradleTreeBuilder = new GradleTreeBuilder(Paths.get(basePath), env, getGradleExeAndJdk(env));
```
Comment (eyalbe4) [inline src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java:50]: Since ```getGradleExeAndJdk(env)``` cam return null. let's just make sure ```new GradleTreeBuilder``` is happy with a null value.

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
